spring.application.name=land-registry

# Database
spring.data.mongodb.uri=mongodb://localhost:27017/landregistry
server.servlet.context-path=/api/v1.0
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# JWT
jwt.secret=T0ew8OEasxJvDFlrI3Wnqt4HJ4rdadQm+LEDg+eRTbg=
jwt.expiration=86400000
